-- Admin-only INSERT on plants (Jul 2026).
-- Powers the "+ Add new plant" workflow on the Human Verify page. Reads stay
-- public, UPDATE was already admin-only; this adds INSERT under the same uid.
-- plants.id is GENERATED BY DEFAULT AS IDENTITY, so the client omits it and
-- the BEFORE INSERT trigger trg_set_plant_batch assigns the batch number.

CREATE POLICY "admin can insert plants" ON public.plants
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = '631158fd-3291-4f4e-9294-cff8abc5d3f8'::uuid);
