-- Seed & Plant Shop database — S1 schema (Aug 2026)
-- See SHOPS_PLAN.md §1. Applied via Supabase MCP execute_sql on ref sysrtpvnkpfuieznfkzb.
-- Admin uid mirrors importer/sql/admin_insert_plants.sql.

-- ---------------------------------------------------------------- organizations
create table if not exists public.organizations (
  id                 bigint generated by default as identity primary key,
  slug               text unique not null,
  name               text not null,
  kind               text,          -- nonprofit | chapter | society | govt_agency | conservation_district
                                    -- | extension | land_trust | botanic_garden | library | coop | other
  scope              text,          -- local | county | regional | state | national
  mission            text,
  focus_areas        text[],
  state              text,
  county             text,
  subregion          text,
  region             text,
  url                text,
  events_url         text,
  contact_email      text,
  membership         text,
  notes              text,
  sources            jsonb default '[]'::jsonb,
  needs_verification boolean not null default true,
  last_verified      date,
  created_at         timestamptz not null default now()
);

-- ---------------------------------------------------------------- vendors
create table if not exists public.vendors (
  id                    bigint generated by default as identity primary key,
  slug                  text unique not null,
  name                  text not null,
  org_id                bigint references public.organizations(id) on delete set null,
  kind                  text,       -- nursery | seed_company | seed_library | seed_swap | plant_sale
                                    -- | conservation_district | botanic_garden | coop | other
  street                text,
  city                  text,
  county                text,
  state                 text,
  postal                text,
  subregion             text,       -- Western NY | Finger Lakes | Central NY | Southern Tier | ...
  region                text,       -- one of the site's 6 regions
  lat                   double precision,
  lon                   double precision,
  address_note          text,
  url                   text,
  catalog_url           text,
  order_form_url        text,
  email                 text,
  phone                 text,
  sells                 boolean default true,
  gives_free            boolean default false,
  membership_required   boolean default false,
  ships                 boolean default false,
  ships_states          text[],
  pickup_only           boolean default false,
  forms                 text[],     -- seed | potted | plug | bare_root | tuber | scion | live_stake
  season_note           text,
  order_window          text,
  hours                 text,
  straight_species_only boolean,
  local_ecotype         boolean,
  nursery_propagated    boolean,
  neonic_free           boolean,
  sourcing_notes        text,
  inventory_mode        text default 'none',  -- feed | vendor_csv | adapter | pdf_annual | manual | none
  inventory_url         text,
  inventory_last_sync   timestamptz,
  notes                 text,
  sources               jsonb default '[]'::jsonb,
  needs_verification    boolean not null default true,
  last_verified         date,
  verified_by           text,
  created_at            timestamptz not null default now()
);
create index if not exists vendors_state_idx     on public.vendors(state);
create index if not exists vendors_subregion_idx on public.vendors(subregion);
create index if not exists vendors_kind_idx      on public.vendors(kind);

-- ---------------------------------------------------------------- sales (D3)
create table if not exists public.sales (
  id                 bigint generated by default as identity primary key,
  slug               text unique not null,
  vendor_id          bigint not null references public.vendors(id) on delete cascade,
  org_id             bigint references public.organizations(id) on delete set null,
  name               text not null,
  kind               text,          -- sale | swap | order_window | open_house | pickup
  starts_on          date,
  ends_on            date,
  starts_at          time,
  ends_at            time,
  order_opens_on     date,
  order_closes_on    date,
  pickup_on          date,
  recurs             text,          -- annual_spring | annual_fall | annual_winter_order | one_off
  venue_name         text,
  street             text,
  city               text,
  county             text,
  state              text,
  lat                double precision,
  lon                double precision,
  url                text,
  price_note         text,
  member_preview     text,
  notes              text,
  source_url         text,
  needs_verification boolean not null default true,
  last_verified      date,
  created_at         timestamptz not null default now()
);
create index if not exists sales_starts_idx on public.sales(starts_on);
create index if not exists sales_vendor_idx on public.sales(vendor_id);

-- ---------------------------------------------------------------- vendor_plants
create table if not exists public.vendor_plants (
  id            bigint generated by default as identity primary key,
  vendor_id     bigint not null references public.vendors(id) on delete cascade,
  plant_id      bigint references public.plants(id) on delete set null,
  sale_id       bigint references public.sales(id) on delete set null,
  raw_name      text,
  raw_sci       text,
  is_cultivar   boolean default false,
  cultivar_name text default '',
  form          text,               -- seed | potted | plug | bare_root | tuber | scion | live_stake
  size          text,
  price_cents   integer,
  unit          text,
  stock         text default 'unknown',  -- in_stock | out | seasonal | unknown
  source        text,               -- feed | vendor_csv | adapter | pdf | manual | user_report
  confidence    text default 'medium',
  url           text,
  first_seen    date default current_date,
  last_seen     date default current_date,
  created_at    timestamptz not null default now()
);
create unique index if not exists vendor_plants_uniq
  on public.vendor_plants(vendor_id, plant_id, form, cultivar_name)
  where plant_id is not null;
create index if not exists vendor_plants_plant_idx  on public.vendor_plants(plant_id);
create index if not exists vendor_plants_vendor_idx on public.vendor_plants(vendor_id);

-- ---------------------------------------------------------------- plant_synonyms (D5)
create table if not exists public.plant_synonyms (
  id       bigint generated by default as identity primary key,
  plant_id bigint not null references public.plants(id) on delete cascade,
  name     text not null,
  kind     text not null default 'sci',   -- sci | common
  source   text
);
create unique index if not exists plant_synonyms_uniq on public.plant_synonyms(lower(name), kind);

-- ---------------------------------------------------------------- matcher staging (D5)
create table if not exists public.vendor_plants_unmatched (
  id                bigint generated by default as identity primary key,
  vendor_id         bigint references public.vendors(id) on delete cascade,
  raw_name          text,
  raw_sci           text,
  form              text,
  seen_count        integer default 1,
  first_seen        date default current_date,
  last_seen         date default current_date,
  resolved_plant_id bigint references public.plants(id) on delete set null,
  dismissed         boolean default false
);

-- ---------------------------------------------------------------- editor intake (§2.4)
create table if not exists public.vendor_imports (
  id           bigint generated by default as identity primary key,
  vendor_id    bigint references public.vendors(id) on delete set null,
  sale_id      bigint references public.sales(id) on delete set null,
  kind         text,     -- vendor | sale | inventory
  mode         text,     -- form | link | upload
  source_url   text,
  storage_path text,
  filename     text,
  mime         text,
  bytes        integer,
  status       text default 'queued',  -- queued | parsed | applied | failed | dismissed
  parsed       jsonb,
  error        text,
  created_by   uuid default auth.uid(),
  created_at   timestamptz not null default now(),
  applied_at   timestamptz
);

-- ---------------------------------------------------------------- shopping list (per user)
create table if not exists public.shopping_list (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  plan_id    uuid not null references public.plans(id) on delete cascade,
  plant_id   bigint not null references public.plants(id) on delete cascade,
  vendor_id  bigint references public.vendors(id) on delete set null,
  qty        integer default 1,
  done       boolean default false,
  note       text,
  created_at timestamptz not null default now()
);
create unique index if not exists shopping_list_uniq
  on public.shopping_list(user_id, plan_id, plant_id, coalesce(vendor_id, 0));

-- ================================================================= RLS
alter table public.organizations           enable row level security;
alter table public.vendors                 enable row level security;
alter table public.sales                   enable row level security;
alter table public.vendor_plants           enable row level security;
alter table public.plant_synonyms          enable row level security;
alter table public.vendor_plants_unmatched enable row level security;
alter table public.vendor_imports          enable row level security;
alter table public.shopping_list           enable row level security;

-- public read (D6) + admin write, for the five catalog tables
do $$
declare t text;
begin
  foreach t in array array['organizations','vendors','sales','vendor_plants','plant_synonyms'] loop
    execute format($f$
      drop policy if exists %1$s_public_read on public.%1$s;
      create policy %1$s_public_read on public.%1$s for select using (true);
      drop policy if exists %1$s_admin_insert on public.%1$s;
      create policy %1$s_admin_insert on public.%1$s for insert
        with check (auth.uid() = '631158fd-3291-4f4e-9294-cff8abc5d3f8'::uuid);
      drop policy if exists %1$s_admin_update on public.%1$s;
      create policy %1$s_admin_update on public.%1$s for update
        using (auth.uid() = '631158fd-3291-4f4e-9294-cff8abc5d3f8'::uuid)
        with check (auth.uid() = '631158fd-3291-4f4e-9294-cff8abc5d3f8'::uuid);
      drop policy if exists %1$s_admin_delete on public.%1$s;
      create policy %1$s_admin_delete on public.%1$s for delete
        using (auth.uid() = '631158fd-3291-4f4e-9294-cff8abc5d3f8'::uuid);
    $f$, t);
  end loop;
end $$;

-- admin-only tables (no public read)
do $$
declare t text;
begin
  foreach t in array array['vendor_plants_unmatched','vendor_imports'] loop
    execute format($f$
      drop policy if exists %1$s_admin_all on public.%1$s;
      create policy %1$s_admin_all on public.%1$s for all
        using (auth.uid() = '631158fd-3291-4f4e-9294-cff8abc5d3f8'::uuid)
        with check (auth.uid() = '631158fd-3291-4f4e-9294-cff8abc5d3f8'::uuid);
    $f$, t);
  end loop;
end $$;

-- own-row, like user_plans / plan_layouts
drop policy if exists shopping_list_select_own on public.shopping_list;
create policy shopping_list_select_own on public.shopping_list for select using (user_id = auth.uid());
drop policy if exists shopping_list_insert_own on public.shopping_list;
create policy shopping_list_insert_own on public.shopping_list for insert
  with check (user_id = auth.uid()
    and exists (select 1 from public.plans p where p.id = shopping_list.plan_id and p.user_id = auth.uid()));
drop policy if exists shopping_list_update_own on public.shopping_list;
create policy shopping_list_update_own on public.shopping_list for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists shopping_list_delete_own on public.shopping_list;
create policy shopping_list_delete_own on public.shopping_list for delete using (user_id = auth.uid());

-- ================================================================= views
-- security_invoker so the caller's RLS applies (Supabase advisor requirement).
create or replace view public.vendor_plant_counts
  with (security_invoker = true) as
select v.id as vendor_id,
       count(*) filter (where vp.plant_id is not null)                          as plant_count,
       count(*) filter (where vp.stock = 'in_stock')                            as in_stock_count,
       max(vp.last_seen)                                                        as last_seen
from public.vendors v
left join public.vendor_plants vp on vp.vendor_id = v.id
group by v.id;

create or replace view public.plant_sources
  with (security_invoker = true) as
select vp.plant_id, vp.vendor_id, v.name as vendor_name, v.kind as vendor_kind,
       v.city, v.state, v.county, v.subregion, v.lat, v.lon,
       v.ships, v.gives_free, v.url,
       vp.form, vp.size, vp.price_cents, vp.unit, vp.stock, vp.is_cultivar,
       vp.cultivar_name, vp.source, vp.last_seen
from public.vendor_plants vp
join public.vendors v on v.id = vp.vendor_id
where vp.plant_id is not null;

create or replace view public.sales_upcoming
  with (security_invoker = true) as
select s.*, v.name as vendor_name, v.kind as vendor_kind, v.subregion as vendor_subregion
from public.sales s
join public.vendors v on v.id = s.vendor_id
where coalesce(s.ends_on, s.starts_on, s.pickup_on, s.order_closes_on)
      >= current_date - interval '1 day';
